version: "3.8"

services:
  db:
    image: postgres:12.4
    container_name: receptai-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: receptai
    ports:
      - '5432:5432'
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d